language: go

go:
- 1.13

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install make; fi

install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.22.2/install.sh | sh -s -- -b $(go env GOPATH)/bin

stages:
  - build
  - build_package
  - test
  - test_required_linters
  - test_optional_linters
  - deploy

build: &build
  stage: build
  install: skip
  if: tag IS NOT present
  script: make GOOS=$GOOS bin

build_package: &build_package
  stage: build_package
  install: skip
  if: tag IS present
  script: make GOOS=$GOOS

deploy: &deploy
  stage: deploy
  install: skip
  if: tag IS present
  deploy:
    - provider: releases
      api_key:
        secure: $GITHUB_API_KEY
      file: $DEPLOY_FILE
      skip_cleanup: true

jobs:
  include:
    - <<: *build
      env:
        - GOOS=linux
      os: linux
    
    - <<: *build
      env:
        - GOOS=windows
      os: windows

    - <<: *build
      env:
        - GOOS=darwin
      os: osx

    - <<: *build_package
      env:
        - GOOS=linux
      os: linux

    - <<: *build_package
      env:
        - GOOS=windows
      os: windows

    - <<: *build_package
      env:
        - GOOS=darwin
      os: osx

    - stage: test
      install: skip
      script:
        - go test -coverprofile=coverage.out -mod=vendor ./cmd/... ./pkg/...
        - go tool cover -func=coverage.out
      os: linux

    - stage: test_required_linters
      script: golangci-lint run --config CI/golangci_required_linters.yml cmd/... pkg/...
      os: linux

    - stage: test_optional_linters
      script: golangci-lint run --config CI/golangci_optional_linters.yml cmd/... pkg/...
      os: linux

    - <<: *deploy
      env:
        - GOOS=linux
        - DEPLOY_FILE=package-linux-amd64-.tar.gz
      os: linux

    - <<: *deploy
      env:
        - GOOS=windows
        - DEPLOY_FILE=package-windows-amd64-.tar.gz
      os: windows

    - <<: *deploy
      env:
        - GOOS=darwin
        - DEPLOY_FILE=package-darwin-amd64-.tar.gz
      os: darwin
