name: Rhoc
on: [push]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    
    - name: Run tests
      run: go test -coverprofile=coverage.out -mod=vendor ./cmd/... ./pkg/...

    - name: Make coverage report
      run: go tool cover -func=coverage.out
    
  lint:
    name: Run linters
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    
    - name: Set up linters
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.22.2/install.sh | sh -s -- -b $(go env GOPATH)/bin
    
    - name: Run required liters
      run: $(go env GOPATH)/bin/golangci-lint run --config CI/golangci_required_linters.yml cmd/... pkg/...

    - name: Run optional linters
      run: $(go env GOPATH)/bin/golangci-lint run --config CI/golangci_optional_linters.yml cmd/... pkg/...
    
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    needs: [test, lint]
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: make bin
